name: Build

on:
  push:
    branches: [ main, master, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo registry
        uses: actions/cache@v5.0.5
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo index
        uses: actions/cache@v5.0.5
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache cargo build
        uses: actions/cache@v5.0.5
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Run tests
        run: cargo test --release

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.1
        with:
          name: hello-rust-zygoon
          path: target/release/hello-rust-zygoon

  snapcraft-pack-amd64:
    name: snapcraft (amd64)
    needs: build
    uses: ./.github/workflows/snapcraft-pack.yml

  snapcraft-pack-arm64:
    name: snapcraft (arm64)
    needs: build
    uses: ./.github/workflows/snapcraft-pack.yml
    with:
      runs-on: ubuntu-24.04-arm

  spread-amd64:
    name: spread (amd64) - ${{ matrix.spread-system }}
    needs: snapcraft-pack-amd64
    strategy:
      matrix:
        spread-system: [ubuntu-cloud-24.04, ubuntu-cloud-26.04]
    uses: ./.github/workflows/spread.yml
    with:
      spread-system: ${{ matrix.spread-system }}
      spread-arch: x86_64
      snap-artifact-name: snap-${{ needs.snapcraft-pack-amd64.outputs.arch }}
      snap-filename: ${{ needs.snapcraft-pack-amd64.outputs.snap-filename }}

  spread-arm64:
    name: spread (arm64 - emulated) - ${{ matrix.spread-system }}
    needs: snapcraft-pack-arm64
    strategy:
      matrix:
        spread-system: [ubuntu-cloud-24.04, ubuntu-cloud-26.04]
    uses: ./.github/workflows/spread.yml
    with:
      spread-system: ${{ matrix.spread-system }}
      spread-arch: aarch64
      snap-artifact-name: snap-${{ needs.snapcraft-pack-arm64.outputs.arch }}
      snap-filename: ${{ needs.snapcraft-pack-arm64.outputs.snap-filename }}

  # Credentials can be exported with:
  # snapcraft export-login --snaps=hello-rust-zygoon --channels=latest/edge --acls=package_release,package_upload EDGE

  snapcraft-upload-amd64:
    name: snapcraft (amd64)
    needs: [snapcraft-pack-amd64, spread-amd64]
    uses: ./.github/workflows/snapcraft-upload.yml
    with:
      artifact-name: snap-x86_64
      snapstore-channel: ${{ vars.SNAPCRAFT_CHANNEL }}
      github-environment: ${{ github.ref_type == 'tag' && 'latest/candidate' || 'latest/edge' }}
      github-deployment: true
    secrets:
      publish-credentials: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

  snapcraft-upload-arm64:
    name: snapcraft (arm64)
    needs: [snapcraft-pack-arm64, spread-arm64]
    uses: ./.github/workflows/snapcraft-upload.yml
    with:
      artifact-name: snap-aarch64
      snapstore-channel: ${{ vars.SNAPCRAFT_CHANNEL }}
      github-environment: ${{ github.ref_type == 'tag' && 'latest/candidate' || 'latest/edge' }}
      github-deployment: true
    secrets:
      publish-credentials: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
